apiVersion: v1
kind: Service
metadata:
  labels:
    app: wil-playground
  name: wil-playground
spec:
  ports:
    - name: wil-playground
      nodePort: 8888
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: wil-playground
  type: NodePort
