
apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  type: LoadBalancer
  selector:
    app: wil-playground
  ports:
  - port: 8888
    nodePort: 8888
    protocol: TCP
    targetPort: 8888
  type: NodePort
